<a href="https://colab.research.google.com/github/kalamanik886/TensorFlow-Tutorial/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installing Tensorflow and Tensorflow GPU

In [6]:
pip install tensorflow

In [7]:
pip install tensorflow-gpu

#Importing TensorFlow

In [2]:
%tensorflow_version 2.x

In [3]:
import tensorflow as tf
print(tf.version)
import numpy as np

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors
#### "A tensor is a generalization of vectors and matrices to potentially higher dimensions.

In [4]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.1416, tf.float64)

# Rank/Degree of Tensors

#### The term rank of a tensor extends the notion of the rank of a matrix in linear algebra, although the term is also often used to mean the order (or degree) of a tensor. The rank of a matrix is the minimum number of column vectors needed to span the range of the matrix.

In [5]:
rank0_tensor = tf.Variable("Rank Zero", tf.string)
rank1_tensor = tf.Variable(["Rank One"], tf.string)
rank2_tensor = tf.Variable([['Rank'],['Two']], tf.string)

#### Determine Rank of Tensor

In [6]:
print(tf.rank(rank0_tensor))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


# Shape of Tensors

#### The shape of the tensor is the dimensionality of the tensor.
#### How many lists and how many elements inside the lists

In [7]:
print(rank0_tensor.shape)
print(rank1_tensor.shape)
print(rank2_tensor.shape)

()
(1,)
(2, 1)


## Changing Shapes
#### The number of elements of a tensor is the product of the sizes of all its shapes.
#### The numer of elements in the reshaped tensor MUST match the number in the original

In [8]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
                                                                          

In [9]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#### Example

In [10]:
mytensor = tf.Variable([[5,6,7,8],[2,9,1,5],[4,8,7,6]], tf.int16)
print(mytensor)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[5, 6, 7, 8],
       [2, 9, 1, 5],
       [4, 8, 7, 6]], dtype=int32)>


#### Rank and Shape

In [11]:
print(tf.rank(mytensor))
print(mytensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(3, 4)


#### About the shapes

In [13]:
print("Type of every element:", mytensor.dtype)
print("Shape of tensor:", mytensor.shape)
print("Elements along axis 0 of tensor:", mytensor.shape[0])
print("Elements along the last axis of tensor:", mytensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(mytensor).numpy())


Type of every element: <dtype: 'int32'>
Shape of tensor: (3, 4)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 4
Total number of elements (3*2*4*5):  12


#### Change the shapes

In [14]:
mytensor2 = tf.reshape(mytensor, [2,6])
print(mytensor2)
mytensor3 = tf.reshape(mytensor, [4,3])
print(mytensor3)
mytensor4 = tf.reshape(mytensor, [6, -1])
print(mytensor4)

tf.Tensor(
[[5 6 7 8 2 9]
 [1 5 4 8 7 6]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[5 6 7]
 [8 2 9]
 [1 5 4]
 [8 7 6]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]
 [2 9]
 [1 5]
 [4 8]
 [7 6]], shape=(6, 2), dtype=int32)


## Indexing & Slicing

In [16]:
mytensor99 = tf.constant([0,1,4,7,89,54,15,36,57,75])
print(mytensor99)
print(mytensor99.numpy())

tf.Tensor([ 0  1  4  7 89 54 15 36 57 75], shape=(10,), dtype=int32)
[ 0  1  4  7 89 54 15 36 57 75]


In [22]:
print("First:" , mytensor99[0].numpy())
print("Fifth:" , mytensor99[4].numpy())
print("Last:" , mytensor99[-1].numpy())
print("Second Last:" , mytensor99[-2].numpy())
print("From 2, before 7:", mytensor99[2:7].numpy())
print("Every other item:", mytensor99[::2].numpy())
print("Reversed:", mytensor99[::-1].numpy())


First: 0
Fifth: 89
Last: 75
Second Last: 57
From 2, before 7: [ 4  7 89 54 15]
Every other item: [ 0  4 89 15 57]
Reversed: [75 57 36 15 54 89  7  4  1  0]


## Types of Tensors


1.   Variable
2.   Constant
3. Place Holder
4. SparseTensor



## Basic math on tensors.
#### addition, element-wise multiplication, and matrix multiplication.

In [41]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[5,6],
                 [7,8]])

In [43]:
print(a)
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [45]:
print(tf.add(a,b)) #addition
print(tf.multiply(a,b)) #element-wise multiplication
print(tf.matmul(a,b)) #matrix multiplication

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [46]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication


tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



## Basic operations on Tensors

In [47]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))


tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)
